spring.application.name=idempotency_gateway

spring.datasource.url=jdbc:postgresql://localhost:5432/idempotency_gateway
spring.datasource.username=idempotency_user
spring.datasource.password=myLovia

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true